[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font"

[font.normal]
family = "MesloLGS Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "command"

[scrolling]
multiplier = 3
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/themes/themes/one_dark.toml"
]
